FROM node:22-alpine AS builder
WORKDIR /app
COPY server/package*.json ./server/
COPY prisma ./prisma
WORKDIR /app/server
RUN npm install
RUN npx prisma generate --schema ../prisma/schema.prisma
COPY server/ .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/server/dist ./dist
COPY --from=builder /app/server/package*.json ./
COPY --from=builder /app/server/node_modules ./node_modules
COPY --from=builder /app/prisma ../prisma
COPY server/prisma/seed.ts ./prisma/seed.ts
ENV NODE_ENV=production
EXPOSE 4000
CMD ["node", "dist/index.js"]
