"""
gen_vocab.py -- Generate a comprehensive word→sign mapping for vocab-10k.json.

Maps the ~5000 most common English words to the closest semantically
appropriate ASL sign key. Words already in sign-mapper's WORD_TO_SIGN are
skipped (they're handled there). This file covers the long tail.

Run from project root:
    python tools/gen_vocab.py

Outputs: extension/content/vocab-10k.json
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent

# ── Available sign keys (our 211 SIGNS) ───────────────────────────────────────
# These are the sign keys we can resolve to a visual pose.
# Unknown words get mapped to their semantically closest one.

# ── Semantic word clusters ────────────────────────────────────────────────────
# Format: sign_key: [list of English words that map to it]
# Priority: frequency first, then semantic accuracy.
# ASL grammar note: articles/auxiliaries are handled by SKIP_WORDS in sign-mapper.

CLUSTERS = {

    # ── Pronouns / Deixis ─────────────────────────────────────────────────────
    'ME':   ['i', 'me', 'my', 'myself', 'mine', 'our', 'ourselves'],
    'YOU':  ['you', 'your', 'yours', 'yourself', 'thou', 'thee'],
    'HE':   ['he', 'him', 'his', 'himself'],
    'SHE':  ['she', 'her', 'hers', 'herself'],
    'THEY': ['they', 'them', 'their', 'themselves', 'those', 'these'],
    'WE':   ['we', 'us', 'ours'],
    'IT':   ['it', 'its', 'itself'],

    # ── Common verbs ──────────────────────────────────────────────────────────
    'GO':   ['go', 'goes', 'going', 'went', 'gone', 'leave', 'leaves', 'leaving',
             'left', 'depart', 'departs', 'exit', 'exits', 'travel', 'travels',
             'move', 'moves', 'moving', 'moved', 'proceed', 'proceeds', 'head',
             'heads', 'headed', 'drive', 'drives', 'drove', 'driven', 'walk',
             'walks', 'walked', 'run', 'runs', 'ran', 'rush', 'rushes'],
    'COME': ['come', 'comes', 'coming', 'came', 'arrive', 'arrives', 'arrived',
             'arrival', 'approach', 'approaches', 'approached', 'return',
             'returns', 'returned', 'reach', 'reaches', 'reached'],
    'STOP': ['stop', 'stops', 'stopped', 'stopping', 'halt', 'halts', 'pause',
             'pauses', 'paused', 'end', 'ends', 'ended', 'ending', 'quit',
             'quits', 'quitting', 'cancel', 'cancels', 'cancelled', 'abort',
             'prevent', 'prevents', 'freeze', 'block', 'blocks'],
    'HELP': ['help', 'helps', 'helped', 'helping', 'helper', 'assist',
             'assists', 'assisted', 'assistance', 'support', 'supports',
             'supported', 'supporting', 'aid', 'aids', 'aided', 'serve',
             'serves', 'served', 'rescue', 'saves', 'saved', 'saving'],
    'GIVE': ['give', 'gives', 'gave', 'given', 'giving', 'offer', 'offers',
             'offered', 'offering', 'provide', 'provides', 'provided',
             'providing', 'deliver', 'delivers', 'delivered', 'send',
             'sends', 'sent', 'sending', 'share', 'shares', 'shared',
             'donate', 'donates', 'donated', 'grant', 'grants', 'granted',
             'supply', 'supplies', 'supplied', 'assign', 'assigns'],
    'WAIT': ['wait', 'waits', 'waited', 'waiting', 'hold', 'holds', 'held',
             'holding', 'stay', 'stays', 'stayed', 'remain', 'remains',
             'remained', 'delay', 'delays', 'delayed', 'hesitate', 'hesitates',
             'pause', 'pending', 'standby'],
    'MAKE': ['make', 'makes', 'made', 'making', 'create', 'creates', 'created',
             'creating', 'build', 'builds', 'built', 'building', 'produce',
             'produces', 'produced', 'producing', 'form', 'forms', 'formed',
             'construct', 'constructs', 'constructed', 'develop', 'develops',
             'developed', 'design', 'designs', 'designed', 'generate',
             'generates', 'generated', 'manufacture', 'manufactures'],
    'SEE':  ['see', 'sees', 'saw', 'seen', 'seeing', 'look', 'looks', 'looked',
             'looking', 'watch', 'watches', 'watched', 'watching', 'view',
             'views', 'viewed', 'viewing', 'observe', 'observes', 'observed',
             'notice', 'notices', 'noticed', 'spot', 'spots', 'spotted',
             'detect', 'detects', 'detected', 'find', 'finds', 'found',
             'finding', 'witness', 'witnesses', 'witnessed', 'identify',
             'identifies', 'identified'],
    'HEAR': ['hear', 'hears', 'heard', 'hearing', 'listen', 'listens',
             'listened', 'listening', 'sounds', 'audio', 'noise', 'noises'],
    'SPEAK': ['speak', 'speaks', 'spoke', 'spoken', 'speaking', 'say',
              'says', 'said', 'saying', 'tell', 'tells', 'told', 'telling',
              'talk', 'talks', 'talked', 'talking', 'communicate',
              'communicates', 'communicated', 'express', 'expresses',
              'expressed', 'mention', 'mentions', 'mentioned', 'state',
              'states', 'stated', 'describe', 'describes', 'described',
              'explain', 'explains', 'explained', 'announce', 'announces',
              'announced', 'respond', 'responds', 'responded', 'reply',
              'replies', 'replied', 'discuss', 'discusses', 'discussed',
              'present', 'presents', 'presented', 'report', 'reports',
              'reported', 'declare', 'declares', 'declared', 'claim',
              'claims', 'claimed', 'argue', 'argues', 'argued'],
    'KNOW': ['know', 'knows', 'knew', 'known', 'knowing', 'realize',
             'realizes', 'realized', 'recognize', 'recognizes', 'recognized',
             'recall', 'recalling', 'remember', 'remembers', 'remembered',
             'aware', 'awareness', 'familiar', 'familiarity'],
    'THINK': ['think', 'thinks', 'thought', 'thinking', 'believe', 'believes',
              'believed', 'believing', 'consider', 'considers', 'considered',
              'considering', 'suppose', 'supposes', 'supposed', 'assume',
              'assumes', 'assumed', 'assume', 'guess', 'guesses', 'guessed',
              'expect', 'expects', 'expected', 'expect', 'imagine',
              'imagines', 'imagined', 'imagine', 'wonder', 'wonders',
              'wondered', 'reflect', 'reflects', 'reflected', 'plan',
              'plans', 'planned', 'planning', 'intend', 'intends',
              'intended', 'decide', 'decides', 'decided', 'deciding',
              'judge', 'judges', 'judged', 'reason', 'reasons', 'reasoned',
              'estimate', 'estimates', 'estimated', 'calculate', 'calculates',
              'calculated', 'analyze', 'analyzes', 'analyzed', 'analysis',
              'analyze', 'examine', 'examines', 'examined', 'evaluate',
              'evaluates', 'evaluated', 'assess', 'assesses', 'assessed',
              'conclude', 'concludes', 'concluded', 'determine', 'determines',
              'determined', 'interpret', 'interprets', 'interpreted',
              'predict', 'predicts', 'predicted', 'suggest', 'suggests',
              'suggested', 'recommend', 'recommends', 'recommended',
              'propose', 'proposes', 'proposed', 'infer', 'infers',
              'inferred', 'deduce', 'deduces', 'deduced', 'conclude',
              'hypothesis', 'hypothesize', 'theorize', 'speculate',
              'speculates', 'speculated'],
    'UNDERSTAND': ['understand', 'understands', 'understood', 'understanding',
                   'comprehend', 'comprehends', 'comprehended', 'comprehension',
                   'grasp', 'grasps', 'grasped', 'follow', 'follows',
                   'followed', 'process', 'processes', 'processed', 'absorb',
                   'absorbs', 'absorbed', 'interpret', 'interprets'],
    'WANT': ['want', 'wants', 'wanted', 'wanting', 'wish', 'wishes', 'wished',
             'wishing', 'desire', 'desires', 'desired', 'hoping', 'hope',
             'hopes', 'hoped', 'crave', 'craves', 'craved', 'prefer',
             'prefers', 'preferred', 'prefer', 'request', 'requests',
             'requested', 'demand', 'demands', 'demanded'],
    'NEED': ['need', 'needs', 'needed', 'needing', 'require', 'requires',
             'required', 'requiring', 'requirement', 'requirements',
             'necessary', 'necessity', 'must', 'essential', 'essentials',
             'important', 'crucial', 'critical', 'vital', 'mandatory'],
    'HAVE': ['have', 'has', 'had', 'having', 'own', 'owns', 'owned', 'owning',
             'possess', 'possesses', 'possessed', 'contain', 'contains',
             'contained', 'include', 'includes', 'included', 'including',
             'hold', 'holds', 'held', 'keep', 'keeps', 'kept', 'keeping',
             'carry', 'carries', 'carried', 'carrying', 'retain', 'retains',
             'retained', 'get', 'gets', 'got', 'gotten', 'getting', 'obtain',
             'obtains', 'obtained', 'acquire', 'acquires', 'acquired',
             'receive', 'receives', 'received', 'receiving', 'earn',
             'earns', 'earned', 'earn'],
    'FEEL': ['feel', 'feels', 'felt', 'feeling', 'emotion', 'emotions',
             'emotional', 'sense', 'senses', 'sensed', 'sensing', 'experience',
             'experiences', 'experienced', 'experiencing', 'sense'],
    'LIKE': ['like', 'likes', 'liked', 'liking', 'enjoy', 'enjoys', 'enjoyed',
             'enjoying', 'prefer', 'favorite', 'favourites', 'appreciate',
             'appreciates', 'appreciated', 'fond', 'admire', 'admires',
             'admired', 'love', 'interested'],
    'LEARN': ['learn', 'learns', 'learned', 'learning', 'study', 'studying',
              'studied', 'studies', 'practice', 'practices', 'practiced',
              'practicing', 'train', 'trains', 'trained', 'training',
              'prepare', 'prepares', 'prepared', 'preparing', 'review',
              'reviews', 'reviewed', 'reviewing', 'master', 'masters',
              'mastered', 'improve', 'improves', 'improved', 'improving',
              'progress', 'progresses', 'progressed', 'develop', 'develops',
              'developed', 'developing', 'acquire', 'skill', 'skills',
              'knowledge', 'education', 'educational', 'educate', 'educates',
              'educated', 'educating', 'research', 'researches', 'researched',
              'researching', 'explore', 'explores', 'explored', 'exploring',
              'investigate', 'investigates', 'investigated', 'discovery',
              'discover', 'discovers', 'discovered', 'discovering'],
    'TEACH': ['teach', 'teaches', 'taught', 'teaching', 'instruct',
              'instructs', 'instructed', 'instructing', 'instruction',
              'demonstrate', 'demonstrates', 'demonstrated', 'demonstrating',
              'explain', 'guide', 'guides', 'guided', 'guiding', 'coach',
              'coaches', 'coached', 'coaching', 'mentor', 'mentors',
              'mentored', 'mentoring', 'tutor', 'tutors', 'tutored'],
    'READ': ['read', 'reads', 'reading', 'book', 'books', 'text', 'texts',
             'article', 'articles', 'chapter', 'chapters', 'page', 'pages',
             'paragraph', 'content', 'document', 'documents', 'passage',
             'passages', 'material', 'materials', 'manuscript', 'novel',
             'novels', 'story', 'stories', 'narrative', 'literature',
             'script', 'scripts', 'paragraph'],
    'WRITE': ['write', 'writes', 'wrote', 'written', 'writing', 'type',
              'types', 'typed', 'typing', 'note', 'notes', 'noted',
              'noting', 'record', 'records', 'recorded', 'recording',
              'draft', 'drafts', 'drafted', 'drafting', 'compose',
              'composes', 'composed', 'composing', 'author', 'authors',
              'authored', 'authoring', 'document', 'documents', 'documented',
              'essay', 'essays', 'report', 'reports', 'paper', 'papers',
              'letter', 'letters', 'email', 'emails', 'message', 'messages',
              'text', 'texts', 'texting', 'blog', 'blogs', 'post', 'posts',
              'article', 'articles', 'submission', 'submit', 'submits'],
    'ANSWER': ['answer', 'answers', 'answered', 'answering', 'response',
               'responses', 'respond', 'responds', 'responded', 'responding',
               'reply', 'replies', 'replied', 'replying', 'solve', 'solves',
               'solved', 'solving', 'solution', 'solutions', 'resolve',
               'resolves', 'resolved'],
    'ASK': ['ask', 'asks', 'asked', 'asking', 'question', 'questions',
            'questioned', 'questioning', 'query', 'queries', 'queried',
            'inquire', 'inquires', 'inquired', 'inquiry', 'request',
            'requests', 'requested', 'requesting'],
    'CALL': ['call', 'calls', 'called', 'calling', 'contact', 'contacts',
             'contacted', 'contacting', 'reach', 'reaches', 'reached',
             'name', 'names', 'named', 'naming', 'invite', 'invites',
             'invited', 'inviting'],
    'BRING': ['bring', 'brings', 'brought', 'bringing', 'carry', 'carries',
              'carried', 'carrying', 'take', 'takes', 'took', 'taken',
              'taking', 'fetch', 'fetches', 'fetched', 'fetching', 'collect',
              'collects', 'collected', 'collecting', 'gather', 'gathers',
              'gathered', 'gathering', 'grab', 'grabs', 'grabbed', 'grabbing',
              'transport', 'transports', 'transported'],
    'CHOOSE': ['choose', 'chooses', 'chose', 'chosen', 'choosing', 'select',
               'selects', 'selected', 'selecting', 'selection', 'pick',
               'picks', 'picked', 'picking', 'decide', 'decides', 'decided',
               'deciding', 'option', 'options', 'prefer', 'prefers',
               'preferred', 'vote', 'votes', 'voted', 'voting', 'elect',
               'elects', 'elected'],
    'CHANGE': ['change', 'changes', 'changed', 'changing', 'modify',
               'modifies', 'modified', 'modifying', 'modification', 'update',
               'updates', 'updated', 'updating', 'adjust', 'adjusts',
               'adjusted', 'adjusting', 'edit', 'edits', 'edited', 'editing',
               'revise', 'revises', 'revised', 'revising', 'revision',
               'transform', 'transforms', 'transformed', 'transforming',
               'shift', 'shifts', 'shifted', 'shifting', 'alter', 'alters',
               'altered', 'altering', 'switch', 'switches', 'switched',
               'switching', 'convert', 'converts', 'converted', 'converting',
               'replace', 'replaces', 'replaced', 'replacing', 'reset',
               'resets', 'improve', 'fix', 'fixes', 'fixed', 'fixing',
               'repair', 'repairs', 'repaired', 'repairing', 'correct',
               'corrects', 'corrected', 'correcting'],
    'CONTINUE': ['continue', 'continues', 'continued', 'continuing',
                 'keep', 'keeps', 'kept', 'keeping', 'maintain', 'maintains',
                 'maintained', 'maintaining', 'persist', 'persists',
                 'persisted', 'persisting', 'proceed', 'proceeds',
                 'proceeded', 'proceeding', 'carry on', 'resume', 'resumes',
                 'resumed', 'resuming', 'follow', 'follows', 'followed',
                 'following', 'continue'],
    'START': ['start', 'starts', 'started', 'starting', 'begin', 'begins',
              'began', 'begun', 'beginning', 'launch', 'launches', 'launched',
              'launching', 'initiate', 'initiates', 'initiated', 'initiating',
              'introduce', 'introduces', 'introduced', 'introducing',
              'introduction', 'open', 'opens', 'opened', 'opening', 'create',
              'establish', 'establishes', 'established', 'establishing',
              'found', 'founds', 'founded', 'founding', 'foundation',
              'setup', 'setup', 'initialize', 'initializes', 'initialized',
              'activate', 'activates', 'activated', 'trigger', 'triggers'],
    'FINISH': ['finish', 'finishes', 'finished', 'finishing', 'complete',
               'completes', 'completed', 'completing', 'completion', 'done',
               'accomplish', 'accomplishes', 'accomplished', 'accomplishing',
               'achieve', 'achieves', 'achieved', 'achieving', 'achievement',
               'success', 'successful', 'succeed', 'succeeds', 'succeeded',
               'conclude', 'concludes', 'concluded', 'concluding', 'close',
               'closes', 'closed', 'closing', 'submit', 'submits', 'submitted',
               'deliver', 'delivers', 'delivered', 'ready', 'final', 'end',
               'over', 'through', 'graduated', 'graduate', 'graduates'],
    'AGAIN': ['again', 'repeat', 'repeats', 'repeated', 'repeating',
              'repetition', 'retry', 'retries', 'retried', 'redo',
              'redo', 'once more', 'another', 'another', 'replay',
              'replays', 'replayed', 'review', 'revisit', 'revisits',
              'revisited', 'rethink', 'reconsider', 'reconsiders'],
    'TRANSLATE': ['translate', 'translates', 'translated', 'translating',
                  'translation', 'translations', 'interpreter', 'interpret',
                  'interprets', 'interpreted', 'interpreting', 'subtitle',
                  'subtitles', 'caption', 'captions', 'captioned', 'captioning',
                  'convert', 'converts', 'converted', 'converting'],

    # ── Descriptors / Adjectives ─────────────────────────────────────────────
    'GOOD': ['good', 'great', 'excellent', 'wonderful', 'fantastic',
             'amazing', 'awesome', 'outstanding', 'superb', 'perfect',
             'well', 'nice', 'fine', 'positive', 'beneficial', 'useful',
             'helpful', 'effective', 'efficient', 'quality', 'superior',
             'ideal', 'optimal', 'solid', 'strong', 'correct', 'right',
             'accurate', 'appropriate', 'suitable', 'proper', 'valid',
             'successful', 'improved', 'better', 'best', 'top'],
    'BAD': ['bad', 'terrible', 'awful', 'horrible', 'poor', 'wrong',
            'incorrect', 'mistake', 'mistakes', 'error', 'errors',
            'problem', 'problems', 'issue', 'issues', 'negative',
            'harmful', 'dangerous', 'wrong', 'failure', 'fail', 'fails',
            'failed', 'failing', 'difficult', 'invalid', 'broken'],
    'BIG': ['big', 'large', 'huge', 'giant', 'enormous', 'massive',
            'vast', 'great', 'major', 'significant', 'substantial',
            'considerable', 'extensive', 'broad', 'wide', 'tall', 'long',
            'high', 'heavy', 'deep', 'thick', 'full', 'maximum', 'maximum',
            'expanded', 'advanced', 'complex', 'comprehensive'],
    'SMALL': ['small', 'little', 'tiny', 'minor', 'minimal', 'brief',
              'short', 'limited', 'simple', 'basic', 'light', 'low',
              'narrow', 'thin', 'few', 'less', 'reduced', 'minimum'],
    'HAPPY': ['happy', 'glad', 'pleased', 'delighted', 'joyful', 'cheerful',
              'excited', 'enthusiastic', 'positive', 'satisfied', 'content',
              'thankful', 'grateful', 'lucky', 'fortunate', 'celebrate',
              'celebrates', 'celebrated', 'celebration', 'enjoy', 'fun',
              'pleasure', 'wonderful'],
    'SAD': ['sad', 'unhappy', 'upset', 'disappointed', 'sorry', 'regret',
            'regrets', 'regretted', 'miss', 'misses', 'missed', 'missing',
            'lonely', 'alone', 'afraid', 'worried', 'anxious', 'nervous',
            'stressed', 'frustrated', 'depressed', 'difficult', 'hard',
            'trouble', 'troubles', 'troubled', 'concern', 'concerns',
            'concerned', 'confusing', 'confused', 'lost'],
    'SAME': ['same', 'similar', 'alike', 'equal', 'equivalent', 'identical',
             'matching', 'consistent', 'related', 'also', 'too', 'either',
             'both', 'together', 'common', 'shared', 'standard'],
    'DIFFERENT': ['different', 'unlike', 'various', 'other', 'another',
                  'separate', 'distinct', 'unique', 'individual', 'diverse',
                  'alternative', 'opposite', 'contrast', 'contrasting',
                  'independent', 'specific', 'particular', 'special'],
    'BEAUTIFUL': ['beautiful', 'pretty', 'lovely', 'gorgeous', 'attractive',
                  'elegant', 'stunning', 'nice', 'wonderful', 'amazing'],
    'IMPORTANT': ['important', 'critical', 'key', 'main', 'primary',
                  'central', 'core', 'fundamental', 'essential', 'significant',
                  'major', 'crucial', 'vital', 'necessary', 'required',
                  'priority', 'valuable', 'relevant', 'meaningful',
                  'noteworthy', 'notable'],
    'CORRECT': ['correct', 'right', 'accurate', 'proper', 'true', 'valid',
                'exact', 'precise', 'appropriate', 'suitable'],
    'DIFFICULT': ['difficult', 'hard', 'challenging', 'complex', 'complicated',
                  'tough', 'demanding', 'impossible', 'impossible', 'advanced',
                  'tricky', 'confusing', 'struggle', 'struggles'],
    'EASY': ['easy', 'simple', 'straightforward', 'clear', 'obvious',
             'basic', 'elementary', 'quick', 'fast', 'efficient'],

    # ── Time ──────────────────────────────────────────────────────────────────
    'NOW':      ['now', 'currently', 'today', 'present', 'currently', 'instantly',
                 'immediately', 'right now', 'at this moment', 'at the moment'],
    'TODAY':    ['today', 'this day', 'nowadays'],
    'TOMORROW': ['tomorrow', 'next day', 'the following day'],
    'YESTERDAY':['yesterday', 'last day', 'the previous day'],
    'MORNING':  ['morning', 'mornings', 'early', 'dawn', 'sunrise', 'am'],
    'NIGHT':    ['night', 'nights', 'evening', 'evenings', 'dark', 'pm',
                 'midnight', 'late', 'dusk', 'sunset'],
    'WEEK':     ['week', 'weeks', 'weekly', 'weekday', 'weekdays', 'weekend',
                 'weekends', 'monday', 'tuesday', 'wednesday', 'thursday',
                 'friday', 'saturday', 'sunday'],
    'LATER':    ['later', 'soon', 'after', 'afterwards', 'then', 'next',
                 'future', 'upcoming', 'following', 'eventually', 'finally',
                 'shortly', 'when', 'once', 'eventually', 'someday'],
    'TIME':     ['time', 'times', 'moment', 'moments', 'period', 'periods',
                 'phase', 'phases', 'stage', 'stages', 'step', 'steps',
                 'hour', 'hours', 'minute', 'minutes', 'second', 'seconds',
                 'month', 'months', 'year', 'years', 'decade', 'century',
                 'schedule', 'schedules', 'scheduled', 'appointment',
                 'appointments', 'date', 'dates', 'session', 'sessions',
                 'term', 'terms', 'semester', 'quarter', 'annual', 'monthly',
                 'daily', 'frequency', 'duration', 'deadline', 'era',
                 'age', 'history', 'historical', 'recent', 'recent',
                 'current', 'past', 'previous', 'former', 'old', 'new',
                 'modern', 'ancient', 'temporary', 'permanent', 'always',
                 'never', 'sometimes', 'often', 'usually', 'generally',
                 'typically', 'regularly', 'constantly', 'continuously',
                 'frequently', 'occasionally', 'rarely', 'seldom'],
    'BEFORE':   ['before', 'earlier', 'previously', 'prior', 'formerly',
                 'initial', 'originally', 'first', 'firstly', 'initially'],
    'AFTER':    ['after', 'following', 'subsequently', 'then', 'next',
                 'later', 'behind', 'beyond', 'since'],

    # ── Places / Locations ────────────────────────────────────────────────────
    'HOME':    ['home', 'house', 'apartment', 'flat', 'residence', 'place',
                'room', 'bedroom', 'kitchen', 'bathroom', 'living room',
                'indoor', 'inside', 'interior', 'local', 'neighborhood'],
    'SCHOOL':  ['school', 'schools', 'education', 'campus', 'building',
                'classroom', 'classrooms', 'library', 'libraries',
                'institution', 'academy', 'institute'],
    'UNIVERSITY': ['university', 'universities', 'college', 'colleges',
                   'department', 'departments', 'faculty', 'academic',
                   'academics', 'graduate', 'undergraduate', 'bachelor',
                   'master', 'phd', 'doctorate', 'degree', 'degrees',
                   'program', 'programs', 'curriculum', 'syllabus',
                   'enrollment', 'enrollment', 'campus', 'dorm', 'dormitory'],
    'WORK':    ['work', 'works', 'worked', 'working', 'job', 'jobs',
                'career', 'careers', 'profession', 'professions',
                'occupation', 'occupations', 'business', 'businesses',
                'company', 'companies', 'organization', 'organizations',
                'office', 'offices', 'workplace', 'workplaces', 'employer',
                'employee', 'employees', 'staff', 'team', 'teams',
                'colleague', 'colleagues', 'coworker', 'coworkers',
                'project', 'projects', 'task', 'tasks', 'position',
                'role', 'roles', 'responsibility', 'responsibilities'],

    # ── People ────────────────────────────────────────────────────────────────
    'PERSON':  ['person', 'people', 'individual', 'individuals', 'human',
                'humans', 'member', 'members', 'participant', 'participants',
                'user', 'users', 'someone', 'anyone', 'everyone',
                'everybody', 'somebody', 'nobody'],
    'FRIEND':  ['friend', 'friends', 'friendship', 'buddy', 'pal',
                'companion', 'companions', 'partner', 'partners',
                'associate', 'associates', 'colleague', 'peer', 'peers',
                'classmate', 'classmates', 'teammate', 'teammates',
                'roommate', 'roommates'],
    'FAMILY':  ['family', 'families', 'relative', 'relatives', 'parent',
                'parents', 'mother', 'father', 'mom', 'dad', 'child',
                'children', 'son', 'daughter', 'sibling', 'siblings',
                'cousin', 'aunt', 'uncle', 'grandmother', 'grandfather',
                'grandparent', 'grandparents', 'wife', 'husband', 'spouse',
                'partner', 'couple', 'household'],
    'STUDENT': ['student', 'students', 'learner', 'learners', 'pupil',
                'pupils', 'scholar', 'scholars', 'intern', 'interns',
                'trainee', 'trainees', 'beginner', 'beginners', 'novice'],
    'TEACHER': ['teacher', 'teachers', 'professor', 'professors',
                'instructor', 'instructors', 'educator', 'educators',
                'tutor', 'tutors', 'mentor', 'mentors', 'coach', 'coaches',
                'trainer', 'trainers', 'lecturer', 'lecturers',
                'facilitator', 'facilitators', 'guide', 'expert', 'experts',
                'specialist', 'specialists', 'authority', 'authorities'],
    'DOCTOR':  ['doctor', 'doctors', 'physician', 'physicians', 'nurse',
                'nurses', 'medical', 'healthcare', 'health', 'hospital',
                'hospitals', 'clinic', 'clinics', 'medicine', 'treatment',
                'treatments', 'therapy', 'therapist', 'therapists',
                'patient', 'patients', 'diagnosis', 'diagnose', 'prescribe',
                'prescription', 'surgery', 'emergency', 'dentist',
                'pharmacist', 'pharmaceutical'],
    'DEAF':    ['deaf', 'deafness', 'hearing impaired', 'hard of hearing',
                'hearing loss', 'asl', 'sign language', 'signing', 'signer',
                'signers', 'interpreter', 'interpreters'],
    'HEARING': ['hearing', 'hearing person', 'listener', 'listeners',
                'audience', 'auditory', 'oral', 'spoken', 'verbal'],
    'BROTHER': ['brother', 'brothers', 'bro', 'sibling', 'male sibling'],
    'SISTER':  ['sister', 'sisters', 'sis', 'female sibling'],
    'BABY':    ['baby', 'babies', 'infant', 'infants', 'toddler', 'toddlers',
                'newborn', 'newborns', 'child', 'kid', 'kids'],

    # ── Objects / Things ──────────────────────────────────────────────────────
    'FOOD':   ['food', 'foods', 'eat', 'eats', 'ate', 'eaten', 'eating',
               'meal', 'meals', 'lunch', 'dinner', 'breakfast', 'snack',
               'snacks', 'drink', 'drinks', 'drank', 'drinking', 'cook',
               'cooks', 'cooked', 'cooking', 'recipe', 'recipes', 'restaurant',
               'restaurants', 'diet', 'nutrition', 'healthy', 'fruit',
               'vegetables', 'meat', 'dessert', 'candy', 'sugar'],
    'WATER':  ['water', 'liquid', 'fluid', 'drink', 'drinks', 'wet',
               'rain', 'ocean', 'sea', 'river', 'lake', 'pool', 'wave'],
    'MONEY':  ['money', 'pay', 'pays', 'paid', 'paying', 'payment',
               'payments', 'cost', 'costs', 'price', 'prices', 'fee',
               'fees', 'salary', 'income', 'budget', 'fund', 'funds',
               'funded', 'funding', 'finance', 'finances', 'financial',
               'invest', 'invests', 'invested', 'investment', 'dollar',
               'dollars', 'cent', 'cents', 'currency', 'bank', 'banks',
               'account', 'accounts', 'loan', 'loans', 'credit', 'debit',
               'cash', 'bill', 'bills', 'charge', 'charges', 'afford',
               'expensive', 'cheap', 'free', 'profit', 'revenue', 'tax'],
    'COMPUTER': ['computer', 'computers', 'laptop', 'laptops', 'desktop',
                 'device', 'devices', 'machine', 'machines', 'screen',
                 'screens', 'monitor', 'monitors', 'keyboard', 'keyboards',
                 'mouse', 'processor', 'data', 'digital', 'software',
                 'hardware', 'system', 'systems', 'technology', 'tech',
                 'program', 'programs', 'application', 'applications',
                 'app', 'apps', 'tool', 'tools', 'platform', 'platforms',
                 'interface', 'interfaces', 'algorithm', 'algorithms',
                 'code', 'coding', 'programming', 'developer', 'developers',
                 'engineer', 'engineers', 'database', 'databases', 'server',
                 'servers', 'cloud', 'ai', 'artificial intelligence',
                 'machine learning', 'neural', 'model', 'models', 'training',
                 'dataset', 'datasets', 'feature', 'features', 'function',
                 'functions', 'class', 'object', 'variable', 'variables',
                 'array', 'loop', 'loops', 'logic', 'binary', 'bit', 'byte',
                 'file', 'files', 'folder', 'folders', 'directory', 'path',
                 'network', 'networks', 'web', 'browser', 'browsers',
                 'search', 'download', 'upload', 'install', 'plugin',
                 'password', 'security', 'encryption', 'protocol', 'api',
                 'framework', 'library', 'module', 'package', 'version',
                 'update', 'upgrade', 'bug', 'error', 'debug', 'test',
                 'testing', 'deploy', 'deployment', 'runtime', 'compiler',
                 'syntax', 'language', 'python', 'javascript', 'java',
                 'html', 'css', 'sql', 'git', 'repository'],
    'INTERNET': ['internet', 'web', 'online', 'website', 'websites', 'url',
                 'link', 'links', 'network', 'wifi', 'connection', 'connect',
                 'connects', 'connected', 'connecting', 'stream', 'streams',
                 'streaming', 'download', 'downloads', 'downloaded',
                 'upload', 'uploads', 'uploaded', 'access', 'server', 'host',
                 'cloud', 'social media', 'platform', 'google', 'youtube',
                 'facebook', 'twitter', 'instagram', 'reddit', 'tiktok',
                 'zoom', 'teams', 'slack', 'discord', 'virtual', 'remote'],
    'PHONE':   ['phone', 'phones', 'mobile', 'cell', 'smartphone', 'call',
                'calls', 'text', 'message', 'messages', 'voicemail',
                'contact', 'dial', 'ring'],
    'VIDEO':   ['video', 'videos', 'film', 'films', 'movie', 'movies',
                'watch', 'watches', 'clip', 'clips', 'recording', 'recordings',
                'stream', 'streams', 'broadcast', 'broadcasts', 'show',
                'shows', 'episode', 'episodes', 'series', 'channel',
                'channels', 'youtube', 'lecture', 'tutorial', 'tutorials'],
    'CAR':     ['car', 'cars', 'vehicle', 'vehicles', 'drive', 'drives',
                'drove', 'driving', 'transport', 'transportation', 'truck',
                'trucks', 'motorcycle', 'bicycle', 'bike'],
    'BUS':     ['bus', 'buses', 'transit', 'train', 'trains', 'subway',
                'metro', 'transportation', 'commute', 'commutes', 'travel'],
    'BOOK':    ['book', 'books', 'textbook', 'textbooks', 'manual', 'manuals',
                'guide', 'guides', 'handbook', 'reference', 'references',
                'publication', 'publications', 'journal', 'journals',
                'magazine', 'magazines', 'chapter', 'chapters', 'edition',
                'volume'],

    # ── Questions ─────────────────────────────────────────────────────────────
    'WHAT':  ['what', 'which', 'whatever', 'whichever'],
    'WHO':   ['who', 'whom', 'whoever', 'whomever'],
    'WHERE': ['where', 'wherever', 'location', 'place', 'direction',
              'position', 'area', 'region', 'spot', 'site'],
    'WHEN':  ['when', 'whenever', 'while'],
    'WHY':   ['why', 'reason', 'reasons', 'because', 'cause', 'causes',
              'purpose', 'purposes', 'goal', 'goals', 'objective',
              'objectives', 'motivation', 'motivations', 'intention',
              'intentions', 'rationale'],
    'HOW':   ['how', 'method', 'methods', 'approach', 'approaches',
              'process', 'procedure', 'procedures', 'technique', 'techniques',
              'way', 'ways', 'strategy', 'strategies', 'means', 'manner',
              'format', 'formats', 'mode', 'step', 'steps', 'instruction',
              'instructions'],

    # ── Numbers ───────────────────────────────────────────────────────────────
    'ONE':   ['one', 'first', '1st', 'single', 'individual', 'unique'],
    'TWO':   ['two', 'second', '2nd', 'double', 'pair', 'both', 'twice',
              'couple', 'dual'],
    'THREE': ['three', 'third', '3rd', 'triple', 'trio'],
    'FOUR':  ['four', 'fourth', '4th', 'quarter'],
    'FIVE':  ['five', 'fifth', '5th'],
    'SIX':   ['six', 'sixth', '6th'],
    'SEVEN': ['seven', 'seventh', '7th'],
    'EIGHT': ['eight', 'eighth', '8th'],
    'NINE':  ['nine', 'ninth', '9th'],
    'ZERO':  ['zero', 'none', 'nothing', 'null', 'empty', 'absent', 'no',
              'negative', 'lack', 'lacks', 'without', 'missing'],

    # ── Educational / Academic vocabulary ────────────────────────────────────
    'CLASS':  ['class', 'classes', 'course', 'courses', 'lesson', 'lessons',
               'unit', 'units', 'module', 'modules', 'topic', 'topics',
               'subject', 'subjects', 'section', 'sections', 'grade',
               'level', 'levels', 'curriculum', 'syllabus'],
    'STUDY':  ['study', 'studies', 'studying', 'studied', 'review', 'reviews',
               'reviewed', 'reviewing', 'practice', 'practices', 'practiced',
               'practicing', 'prepare', 'prepares', 'prepared', 'preparing',
               'preparation', 'revision', 'memorize', 'memorizes', 'memorized',
               'memorize', 'focus', 'focuses', 'focused', 'focusing',
               'concentrate', 'concentrates', 'concentrated'],
    'TEST':   ['test', 'tests', 'tested', 'testing', 'quiz', 'quizzes',
               'evaluate', 'evaluates', 'evaluated', 'evaluation', 'measure',
               'measures', 'measured', 'measuring', 'assessment', 'assess',
               'assesses', 'assessed', 'assessing', 'check', 'checks',
               'checked', 'checking', 'verify', 'verifies', 'verified',
               'verify', 'validate', 'validates', 'validated', 'proof',
               'prove', 'proves', 'proved', 'proven'],
    'EXAM':   ['exam', 'exams', 'examination', 'examinations', 'midterm',
               'midterms', 'final', 'finals', 'certification', 'certifications',
               'certificate', 'certificates', 'credential', 'credentials',
               'qualification', 'qualifications'],
    'HOMEWORK': ['homework', 'assignment', 'assignments', 'exercise',
                 'exercises', 'problem', 'problems', 'task', 'tasks',
                 'activity', 'activities', 'project', 'projects', 'work',
                 'worksheet', 'worksheets', 'drill', 'drills'],
    'GRADE':  ['grade', 'grades', 'graded', 'grading', 'score', 'scores',
               'scored', 'scoring', 'mark', 'marks', 'marked', 'marking',
               'result', 'results', 'performance', 'achievement', 'level',
               'rating', 'rankings', 'rank', 'gpa', 'point', 'points',
               'percentage', 'pass', 'passes', 'passed', 'passing', 'fail',
               'fails', 'failed', 'failing', 'distinction', 'merit',
               'credit', 'scholarship'],
    'LECTURE': ['lecture', 'lectures', 'lectured', 'lecturing', 'presentation',
                'presentations', 'talk', 'talks', 'seminar', 'seminars',
                'workshop', 'workshops', 'webinar', 'webinars', 'session',
                'sessions', 'class', 'conference', 'conferences', 'meeting',
                'meetings', 'discussion', 'discussions'],
    'QUESTION': ['question', 'questions', 'quiz', 'quizzes', 'test',
                 'inquiry', 'inquiries', 'doubt', 'doubts', 'unclear',
                 'unclear', 'prompt', 'prompts'],
    'TRANSLATE': ['translate', 'translates', 'translated', 'translating',
                  'translation', 'translations', 'interpret', 'interprets',
                  'interpreted', 'interpreter', 'language', 'languages',
                  'caption', 'captions', 'subtitle', 'subtitles', 'convert',
                  'converts', 'converted'],

    # ── Math / Science vocabulary ─────────────────────────────────────────────
    'THINK': ['calculate', 'calculates', 'calculated', 'calculate',
              'compute', 'computes', 'computed', 'computing', 'solve',
              'solves', 'solved', 'solving', 'formula', 'formulas',
              'equation', 'equations', 'theorem', 'theorems', 'proof',
              'proofs', 'hypothesis', 'theory', 'theories', 'model',
              'experiment', 'experiments', 'observation', 'observations',
              'data', 'result', 'results', 'conclusion', 'conclusions',
              'concept', 'concepts', 'principle', 'principles', 'law',
              'laws', 'definition', 'definitions', 'property', 'properties',
              'variable', 'variables', 'constant', 'function', 'functions',
              'graph', 'graphs', 'chart', 'charts', 'table', 'tables',
              'statistics', 'statistic', 'average', 'mean', 'median', 'mode',
              'probability', 'distribution', 'analysis', 'analyze',
              'analyzes', 'analyzed', 'syntax', 'logic', 'logical'],

    # ── Emotion / State ───────────────────────────────────────────────────────
    'LOVE':  ['love', 'loves', 'loved', 'loving', 'adore', 'adores',
              'adored', 'adoring', 'care', 'cares', 'cared', 'caring',
              'cherish', 'cherishes', 'cherished', 'cherishing', 'heart',
              'hearts', 'passion', 'passions', 'passionate', 'devoted',
              'devotion', 'affection', 'affections', 'fond', 'fondness',
              'romance', 'romantic'],
    'TIRED': ['tired', 'exhausted', 'fatigue', 'fatigued', 'sleepy',
              'drowsy', 'worn', 'weary', 'burnout', 'burned out', 'drained',
              'rest', 'resting', 'rested', 'sleep', 'sleeps', 'slept',
              'sleeping', 'relax', 'relaxes', 'relaxed', 'relaxing', 'break',
              'breaks', 'pause', 'pauses', 'stop', 'recover', 'recovery'],
    'EXCITED': ['excited', 'exciting', 'enthusiasm', 'enthusiastic',
                'eager', 'eagerness', 'motivate', 'motivated', 'motivation',
                'inspire', 'inspired', 'inspiration', 'energetic', 'energy',
                'passionate', 'passionate', 'proud', 'pride', 'confident',
                'confidence', 'optimistic', 'hope', 'hopeful', 'positive',
                'passionate', 'engaging', 'interesting', 'interest',
                'fascinating', 'fascination', 'surprise', 'surprised',
                'unexpected', 'new', 'discovery', 'innovative', 'innovation',
                'creative', 'creativity'],

    # ── Misc. high-frequency words ────────────────────────────────────────────
    'YES':   ['yes', 'yeah', 'yep', 'sure', 'definitely', 'absolutely',
              'certainly', 'of course', 'agree', 'agrees', 'agreed',
              'agreeing', 'agree', 'confirm', 'confirms', 'confirmed',
              'approve', 'approves', 'approved', 'accept', 'accepts',
              'accepted', 'correct', 'right', 'true', 'positive',
              'affirmative', 'okay', 'ok', 'alright', 'fine', 'exactly',
              'indeed', 'precisely', 'absolutely', 'certainly'],
    'NO':    ['no', 'nope', 'not', 'never', 'neither', 'nor', 'refuse',
              'refuses', 'refused', 'deny', 'denies', 'denied', 'reject',
              'rejects', 'rejected', 'disagree', 'disagrees', 'disagreed',
              'oppose', 'opposes', 'opposed', 'wrong', 'false', 'incorrect',
              'unable', 'cannot', "can't", "won't", "don't", "doesn't",
              "haven't", "hasn't", "didn't", "wouldn't", "shouldn't",
              "couldn't", "isn't", "aren't", "wasn't", "weren't"],
    'PLEASE': ['please', 'kindly', 'gently', 'politely', 'request',
               'requests', 'requesting'],
    'SORRY':  ['sorry', 'apologize', 'apologizes', 'apologized', 'apology',
               'apologies', 'regret', 'regrets', 'regretted', 'excuse',
               'excuses', 'excuse me', 'pardon', 'pardons', 'forgive',
               'forgives', 'forgave', 'forgiven'],
    'THANK_YOU': ['thank', 'thanks', 'thank you', 'grateful', 'gratitude',
                  'appreciate', 'appreciates', 'appreciated', 'appreciation',
                  'acknowledged', 'acknowledge'],

    # ── Directions / Positions ────────────────────────────────────────────────
    'UP':    ['up', 'above', 'over', 'top', 'above', 'upper', 'higher',
              'highest', 'increase', 'increases', 'increased', 'increasing',
              'rise', 'rises', 'rose', 'risen', 'rising', 'above'],
    'DOWN':  ['down', 'below', 'under', 'bottom', 'lower', 'lowest',
              'decrease', 'decreases', 'decreased', 'decreasing', 'fall',
              'falls', 'fell', 'falling', 'drop', 'drops', 'dropped',
              'dropping', 'reduce', 'reduces', 'reduced', 'reducing'],

    # ── Additional topics from Coursera/YouTube ────────────────────────────────
    'THINK': ['concept', 'concepts', 'idea', 'ideas', 'approach', 'approaches',
              'philosophy', 'philosophical', 'abstract', 'abstraction',
              'reflect', 'reflection', 'mindset', 'perspective',
              'perspectives', 'viewpoint', 'viewpoints', 'insight',
              'insights', 'insight', 'opinion', 'opinions', 'argument',
              'arguments', 'premise', 'premises', 'argument', 'position',
              'conclusion', 'conclusions', 'implication', 'implications'],
    'KNOW':  ['information', 'fact', 'facts', 'detail', 'details',
              'context', 'background', 'overview', 'summary', 'summaries',
              'definition', 'definitions', 'example', 'examples', 'instance',
              'instances', 'case', 'cases', 'scenario', 'scenarios',
              'evidence', 'evidences', 'proof', 'source', 'sources',
              'reference', 'references', 'resource', 'resources'],
}

def main():
    out_path = ROOT / 'extension' / 'content' / 'vocab-10k.json'

    # Build flat word→sign_key mapping, skipping duplicates (first cluster wins)
    mapping = {}
    for sign_key, words in CLUSTERS.items():
        for word in words:
            word_lower = word.lower().strip()
            if word_lower and word_lower not in mapping:
                mapping[word_lower] = sign_key

    print(f'Generated {len(mapping)} word mappings -> {len(set(mapping.values()))} unique sign keys')

    # Show some stats
    from collections import Counter
    key_freq = Counter(mapping.values())
    print('Most-used sign keys:', key_freq.most_common(10))

    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(mapping, f, indent=2, sort_keys=True, ensure_ascii=False)
    print(f'Saved -> {out_path}')

if __name__ == '__main__':
    main()
